### Fetches `Blog` resources
GET http://localhost:3001/api/blogs

### Send POST request with json body
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Blog 3",
  "author": "John 3",
  "url": "https://google.com",
  "likes": 0
}

### Removes the identified `Blogs` resource
DELETE http://localhost:3001/api/blogs/644fb280bd76d5ce6b9df935

### Send PUT request with json body
PUT http://localhost:3001/api/blogs/644fb280bd76d5ce6b9df934
Content-Type: application/json

{
  "likes": "21"
}

###
