### Fetches `User` resources
GET http://localhost:3001/api/users

### Send POST request with json body
POST http://localhost:3001/api/users/
Content-Type: application/json

//{
//  "username": "artdev",
//  "name": "Art",
//  "password": "salainen"
//}
{
  "username": "testuser",
  "name": "Test User",
  "password": "testuser"
}

###
