### Fetches All `Persons` resource
GET http://localhost:3001/api/persons

### Fetches a single `Person` resource
GET http://localhost:3001/api/persons/2

### Removes the identified `Person` resource
DELETE http://localhost:3001/api/persons/644980a2ae6e6d1364f8253c

### Creates new `Person` resource
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "John D",
  "number": "12-34-567890"
}

###